// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64          `json:"id"`
	Owner         string         `json:"owner"`
	Balance       int64          `json:"balance"`
	Currency      string         `json:"currency"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	MarkForDelete bool           `json:"mark_for_delete"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount        int64          `json:"amount"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	MarkForDelete bool           `json:"mark_for_delete"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// mmust be positive
	Amount        int64          `json:"amount"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	MarkForDelete bool           `json:"mark_for_delete"`
}

type User struct {
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	FullName          string         `json:"full_name"`
	Email             string         `json:"email"`
	PasswordUpdatedAt time.Time      `json:"password_updated_at"`
	CreatedBy         sql.NullString `json:"created_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	UpdatedAt         time.Time      `json:"updated_at"`
	MarkForDelete     bool           `json:"mark_for_delete"`
}
